staff_chat_id: '-1002021410367'
owner_id: '6656534823'
bot_token: '6705004892:AAGRlCGEbYPjN3fyOQE12Y9a4XXitnk5bN4'
min_users_in_group: 1000
default_message: 'OlÃ¡ acesse'
default_rotational_midia_path: 'midias'
telegram_api_id: 22580021
telegram_api_hash: 2f339911b6c7244bec540652f2859a65
parse_mode: 'HTML'
start_command_text: "ğŸ˜Š Seja bem-vindo ao nosso serviÃ§o automatizado de parcerias!\n\nğŸŒŸ FUNCIONAMENTO:\n\nQuando divulgarmos links nos seus grupos, faremos o mesmo com o seu link em outros grupos.\n\nğŸ¤— PARCERIA EQUILIBRADA!\n\nÃ‰ importante manter as listas compartilhadas no seu grupo por, no mÃ­nimo, â³ 24 horas para garantir a visibilidade do seu link.\n\nğŸ”µ CRITÃ‰RIOS:\n\nO histÃ³rico de mensagens do grupo deve estar ativado.\n\nO grupo deve ter atividades regulares ou conteÃºdo de mÃ­dia.\n\nO grupo deve ter um mÃ­nimo de 300 participantes.\n\nConteÃºdo ilegal Ã© estritamente proibido.\n\nManutenÃ§Ã£o das listas compartilhadas por pelo menos 24 horas.\n\nToque em \"ğŸ“ Participar da lista\" para se juntar!"
horarios:
  - "12:00"
  - "14:19"
  - "20:00"